Laboratorio.Core.MVC/Areas/Servicios/Controllers/EstudiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Laboratorio.Core.DAL.Data;
using Newtonsoft.Json;

namespace Laboratorio.Core.MVC.Areas.Servicios.Controllers
{
    public class EstudiosController : Controller
    {
        private mmadatabaseEntities db = new mmadatabaseEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string CrearEstudio(string nombre, decimal costo, string grupo, string idPerfil)
        {
            try
            {
                var estudio = new lab_Estudios
                {
                    Id = Guid.NewGuid(),
                    Nombre = nombre,
                    Costo = costo,
                    Grupo = grupo
                };

                db.lab_Estudios.Add(estudio);
                db.SaveChanges();

                if (idPerfil!="null")
                {
                    var guidIdPerfil = Guid.Parse(idPerfil);
                    var perfil = db.lab_Perfiles.Find(guidIdPerfil);
                    perfil.lab_Estudios.Add(estudio);
                    db.SaveChanges();
                }

                return "Ok";
            }
            catch (Exception e)
            {
                return "Error";
            }
        }

        [HttpPost]
        public string CrearRelacion(string selected, string idPerfil)
        {
            try
            {
                if (idPerfil != "null")
                {
                    var guidIdPerfil = Guid.Parse(idPerfil);
                    var perfil = db.lab_Perfiles.Find(guidIdPerfil);

                    var guidIdEstudios = Guid.Parse(selected);
                    var estudio = db.lab_Estudios.Find(guidIdEstudios);

                    perfil.lab_Estudios.Add(estudio);
                    db.SaveChanges();
                }

                return "Ok";
            }
            catch (Exception e)
            {
                return "Error";
            }
        }

        [HttpGet]
        public string ObtenerEstudios(string idPerfil)
        {
            if (idPerfil == null || idPerfil == "undefined" || idPerfil == "null")
            {
                var estudios = db.lab_Estudios.Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.Costo,
                    a.Grupo
                }).OrderBy(o => o.Nombre);

                var obj = JsonConvert.SerializeObject(new {estudios});

                return obj;
            }
            else
            {
                var guidIdPerfil = Guid.Parse(idPerfil);

                var estudios = db.lab_Estudios.Where(e =>e.lab_Perfiles.Contains(e.lab_Perfiles.FirstOrDefault(p => p.Id == guidIdPerfil))).Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.Costo,
                    a.Grupo
                }).ToList();

                var obj_x_perfil = JsonConvert.SerializeObject(new { estudios });

                return obj_x_perfil;
            }
        }

        [HttpGet]
        public string ObtenerEstudiosDisponibles(string idPerfil)
        {
            if (idPerfil == null || idPerfil == "undefined" || idPerfil == "null")
            {
                //aquí no se debería meter, no puede venir idPerfil ya que la consulta es con base en el idPerfil
                var estudios = db.lab_Estudios.Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.Costo,
                    a.Grupo
                }).OrderBy(o => o.Nombre);

                var obj = JsonConvert.SerializeObject(new {estudios});

                return obj;
            }
            else
            {
                var guidIdPerfil = Guid.Parse(idPerfil);

                var estudiosComp = db.lab_Estudios.Where(e =>e.lab_Perfiles.Contains(e.lab_Perfiles.FirstOrDefault(p => p.Id == guidIdPerfil))).Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.Costo,
                    a.Grupo
                }).ToList();

                var estudiosAll = db.lab_Estudios.Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.Costo,
                    a.Grupo
                }).ToList();

                var estudios = estudiosAll.Except(estudiosComp).Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.Costo,
                    a.Grupo
                }).ToList();

                var obj_x_perfil = JsonConvert.SerializeObject(new { estudios });

                return obj_x_perfil;
            }
        }

        [HttpPost]
        public string BorrarEstudio(string value)
        {
            try
            {
                var guidValue = Guid.Parse(value);
                var estudio = db.lab_Estudios.Find(guidValue);
                db.lab_Estudios.Remove(estudio);
                db.SaveChanges();

                return "Ok";
            }
            catch (Exception e)
            {
                return "Error";
            }
        }

        [HttpPost]
        public string BorrarRelacion(string value, string idPerfil)
        {
            try
            {
                if (idPerfil != "null")
                {
                    var guidIdEstudio = Guid.Parse(value);
                    var estudio = db.lab_Estudios.Find(guidIdEstudio);
                    var guidIdPerfil = Guid.Parse(idPerfil);
                    var perfil = db.lab_Perfiles.Find(guidIdPerfil);
                    perfil.lab_Estudios.Remove(estudio);
                    db.SaveChanges();
                }

                return "Ok";
            }
            catch (Exception e)
            {
                return "Error";
            }
        }

        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lab_Estudios lab_Estudios = db.lab_Estudios.Find(id);
            if (lab_Estudios == null)
            {
                return HttpNotFound();
            }
            return View(lab_Estudios);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Costo")] lab_Estudios lab_Estudios)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lab_Estudios).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lab_Estudios);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Laboratorio.Core.MVC/Areas/Servicios/Controllers/GeneralController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laboratorio.Core.DAL.Data;
using Microsoft.Owin.Security.Provider;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Laboratorio.Core.MVC.Areas.Servicios.Controllers
{
    public class GeneralController : Controller
    {
        private mmadatabaseEntities db = new mmadatabaseEntities();

        // GET: Servicios/General
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult PruebaLaboratorio()
        {
            return View();
        }

        [HttpPost]
        public JObject ObtenerItemsPorPrueba(List<string> checkedNamesPerfiles, List<string> checkedNamesEstudios)
        {
            dynamic pruebaLaboratorio = new JObject();
            pruebaLaboratorio.Perfiles = new JArray();

            if (checkedNamesPerfiles!=null)
            {
                foreach (var strIdPerfil in checkedNamesPerfiles)
                {
                    var guidIdPerfil = Guid.Parse(strIdPerfil);
                    var perfil = db.lab_Perfiles.FirstOrDefault(e => e.Id == guidIdPerfil);

                    dynamic perfiles = new JObject();
                    perfiles.Id = perfil.Id;
                    perfiles.Nombre = perfil.Nombre;
                    perfiles.Estudios = new JArray();

                    var listIdEstudios = new List<string>();
                    foreach (var estudios in perfil.lab_Estudios)
                    {
                        listIdEstudios.Add(estudios.Id.ToString());
                    }

                    var itemsPorEstudios = ObtenerItemsPorEstudio(listIdEstudios);
                    perfiles.Estudios = itemsPorEstudios;

                    pruebaLaboratorio.Perfiles.Add(perfiles);
                }
            }

            if (checkedNamesEstudios!=null)
            {
                dynamic perfilX = new JObject();
                perfilX.Id = "-";
                perfilX.Nombre = "-";
                perfilX.Estudios = new JArray();
                perfilX.Estudios = ObtenerItemsPorEstudio(checkedNamesEstudios);
                pruebaLaboratorio.Perfiles.Add(perfilX);
            }

            return pruebaLaboratorio;
        }

        private JArray ObtenerItemsPorEstudio(List<string> checkedNamesEstudios)
        {
            dynamic Estudios = new JArray();


            foreach (var strIdEstudio in checkedNamesEstudios)
            {
                var guidIdEstudio = Guid.Parse(strIdEstudio);
                var estudio = db.lab_Estudios.FirstOrDefault(e => e.Id == guidIdEstudio);

                dynamic estudios = new JObject();
                estudios.Id = estudio.Id;
                estudios.Nombre = estudio.Nombre;
                estudios.Elementos = new JArray();

                foreach (var elemento in estudio.lab_Elementos)
                {
                    dynamic elementos = new JObject();
                    elementos.Id = elemento.Id;
                    elementos.Nombre = elemento.Nombre;

                    estudios.Elementos.Add(elementos);
                }

                Estudios.Add(estudios);
            }

            return Estudios;
        }
    }
}

Laboratorio.Core.MVC/Areas/Servicios/Controllers/PerfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Laboratorio.Core.DAL.Data;
using Newtonsoft.Json;

namespace Laboratorio.Core.MVC.Areas.Servicios.Controllers
{
    public class PerfilesController : Controller
    {
        private mmadatabaseEntities db = new mmadatabaseEntities();
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string CrearPerfil(string nombre, decimal costo, string grupo)
        {
            try
            {
                var perfil = new lab_Perfiles
                {
                    Id = Guid.NewGuid(),
                    Nombre = nombre,
                    Costo = costo,
                    Grupo = grupo
                };


                db.lab_Perfiles.Add(perfil);
                db.SaveChanges();

                return "Ok";
            }
            catch (Exception e)
            {
                return "Error";
            }
        }

        [HttpGet]
        public string ObtenerPerfiles(string idEstudios)
        {
            if (idEstudios == null || idEstudios == "undefined")
            {
                var perfiles = db.lab_Perfiles.Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.Costo,
                    a.Grupo
                }).OrderBy(o => o.Nombre);

                var obj = JsonConvert.SerializeObject(new {perfiles});

                return obj;
            }
            else
            {
                var guidIdEstudio = Guid.Parse(idEstudios);

                var perfiles = db.lab_Perfiles.Where(p => p.lab_Estudios.Contains(p.lab_Estudios.FirstOrDefault(e => e.Id == guidIdEstudio))).Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.Costo,
                    a.Grupo
                }).ToList();

                var obj_x_estudio = JsonConvert.SerializeObject(new { perfiles });

                return obj_x_estudio;
            }

        }

        [HttpPost]
        public string BorrarPerfil(string value)
        {
            try
            {
                var guidValue = Guid.Parse(value);
                var perfil = db.lab_Perfiles.Find(guidValue);
                db.lab_Perfiles.Remove(perfil);
                db.SaveChanges();

                return "Ok";
            }
            catch (Exception e)
            {
                return "Error";
            }
        }
        
        
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lab_Perfiles lab_Perfiles = db.lab_Perfiles.Find(id);
            if (lab_Perfiles == null)
            {
                return HttpNotFound();
            }
            return View(lab_Perfiles);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,Costo")] lab_Perfiles lab_Perfiles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lab_Perfiles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lab_Perfiles);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Laboratorio.Core.MVC/Areas/Servicios/Views/General/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_NiftyLayout.cshtml";
}

<link href="~/Scripts/offline-theme-default.css" rel="stylesheet" />
<script src="~/Scripts/offline.min.js"></script>

<script>
    $(function(){

        var
            $online = $('.online'),
            $offline = $('.offline');

        Offline.on('confirmed-down', function () {
            $online.fadeOut(function () {
                $offline.fadeIn();
            });
        });

        Offline.on('confirmed-up', function () {
            $offline.fadeOut(function () {
                $online.fadeIn();
            });
        });

    });
</script>

<style>
    .isActive {
        background-color: #e8e8e8;
    }
</style>

<div class="row">
    <div class="col-md-4">
        <div id="app-main">
            <button class="btn btn-block btn-rounded btn-outline-primary" v-on:click='refreshAllEstudios'>Refrescar</button>
            <br />
        </div>
        <div id="partialView_Perfiles"></div>
    </div>
    <div class="col-md-8">
        <div id="partialView_Estudios"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div id="partialView_Elementos"></div>
    </div>
</div>

<script>
    $('#partialView_Perfiles').load('@(Url.Action("Index", "Perfiles", new {}))');
    $('#partialView_Estudios').load('@(Url.Action("Index", "Estudios", new {}))');
    $('#partialView_Elementos').load('@(Url.Action("Index", "Elementos", new {}))');

    const appMain=new Vue({
        el: '#app-main',
        data: {
            msg:''
        },
        methods: {
            refreshAllEstudios() {
                appEstudios.showRemoveRelation = false;
                appEstudios.showRemoveElement = true;
                appPerfiles.showRemoveElement = true;
                appEstudios.refresh();
                appPerfiles.refresh();
                appElementos.removeElementsFromList();
                appPerfiles.activeIndex = null;
                appEstudios.activeIndex = null;
            }
        }
    })
</script>

Laboratorio.Core.MVC/Areas/Servicios/Views/General/PruebaLaboratorio.cshtml
@{
    ViewBag.Title = "PruebaLaboratorio";
    Layout = "~/Views/Shared/_NiftyLayout.cshtml";
}

<div id="app-pruebaLaboratorio">
    <div v-show="showLabItems">
        <div class="row">
            <div class="col-md-6">
                <button v-on:click="realizarPrueba" class="btn btn-lg btn-rounded btn-primary">Aceptar</button>
                <h1>Pefiles</h1>
                <div v-for="perfil in perfiles" class="form-inline">
                    <input type="checkbox" v-bind:id="perfil.Id" v-bind:value="perfil.Id" v-model="checkedNamesPerfiles">
                    <label v-bind:for="perfil.Id" class="text-info text-2x text-thin">{{perfil.Nombre}}</label>
                </div>

                <h1>Estudios</h1>
                <div v-for="estudio in estudios">
                    <input type="checkbox" v-bind:id="estudio.Id" v-bind:value="estudio.Id" v-model="checkedNamesEstudios">
                    <label v-bind:for="estudio.Id" class="text-info text-2x text-thin">{{estudio.Nombre}}</label>
                </div>
            </div>
            <div class="col-md-6">
                
            </div>
        </div>
    </div>
    
    <div v-show="showForm">
        <div class="sk-three-bounce">
            <div class="sk-child sk-bounce1"></div>
            <div class="sk-child sk-bounce2"></div>
            <div class="sk-child sk-bounce3"></div>
        </div>
        <div v-for="perfil in pruebaLaboratorio.Perfiles">
            <h3 class="">{{perfil.Nombre}}</h3>
            <div v-for="estudio in perfil.Estudios">
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-bordered-info">
                            <div class="panel-heading">
                                <h3 class="panel-title">{{estudio.Nombre}}</h3>
                            </div>
                            <div class="panel-body">
                                <div v-for="elemento in estudio.Elementos">
                                    <div class="col-md-4">
                                        <label class="text-sm">{{elemento.Nombre}}</label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    const appPruebaLaboratorio = new Vue({
        el: '#app-pruebaLaboratorio',
        data: {
            perfiles: [],
            estudios: [],
            checkedNamesPerfiles: [],
            checkedNamesEstudios: [],
            showLabItems: true,
            showForm: false,
            pruebaLaboratorio:""
        },
        created() {
            fetch('@Url.Action("ObtenerPerfiles", "Perfiles")')
                .then(response => response.json())
                .then(json => { this.perfiles = json.perfiles });

            fetch('@Url.Action("ObtenerEstudios", "Estudios")')
                .then(response => response.json())
                .then(json => { this.estudios = json.estudios });
        },
        methods: {
            realizarPrueba() {
                this.showLabItems = !this.showLabItems;
                this.showForm = !this.showForm;
                let checkedNamesPerfiles = this.checkedNamesPerfiles;
                let checkedNamesEstudios = this.checkedNamesEstudios;

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("ObtenerItemsPorPrueba", "General")',
                    data: { checkedNamesPerfiles, checkedNamesEstudios },
                    success: function(result, status, xhr) {
                        if (result.includes("Error")) {
                            msgAlert(result, "danger");
                        } else {
                            appPruebaLaboratorio.pruebaLaboratorio = JSON.parse(result);
                            $('.sk-three-bounce').hide();
                        }
                    },
                    error: function(xhr, status, error) {
                        var msg = '<span class="text-bold">' +
                            error +
                            '</span><br/>Estatus: ' +
                            xhr.status +
                            '<br/>Descripción: ' +
                            xhr.statusText;
                        msgAlert(msg, "danger");
                    }
                });
            }
        }
    });

    function msgAlert(message, type) {
        $.niftyNoty({
            type: type,
            icon: 'demo-pli-information icon-3x',
            message: message,
            container: 'floating',
            timer: 10000
        });
    }

</script>