Laboratorio.Core.MVC/Areas/Servicios/Controllers/ElementosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Laboratorio.Core.DAL.Data;
using Newtonsoft.Json;

namespace Laboratorio.Core.MVC.Areas.Servicios.Controllers
{
    public class ElementosController : Controller
    {
        private mmadatabaseEntities db = new mmadatabaseEntities();

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public string CrearElemento(string nombre, string unidadMedida, string notas, string idEstudio)
        {
            try
            {
                var elemento = new lab_Elementos
                {
                    Id = Guid.NewGuid(),
                    Nombre = nombre,
                    UnidadMedida = unidadMedida,
                    Notas = notas
                };


                db.lab_Elementos.Add(elemento);
                db.SaveChanges();

                if (idEstudio != "null")
                {
                    var guidIdEstudio = Guid.Parse(idEstudio);
                    var estudio = db.lab_Estudios.Find(guidIdEstudio);
                    estudio.lab_Elementos.Add(elemento);
                    db.SaveChanges();
                }

                return "Ok";
            }
            catch (Exception e)
            {
                return "Error";
            }
        }

        [HttpGet]
        public string ObtenerElementos(string idEstudios)
        {
            if (idEstudios == null || idEstudios == "undefined" || idEstudios == "null")
            {
                var elementos = db.lab_Elementos.Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.UnidadMedida,
                    a.Notas
                }).OrderBy(o => o.Nombre);

                var obj = JsonConvert.SerializeObject(new { elementos });

                return obj;
            }
            else
            {
                var guidIdEstudio = Guid.Parse(idEstudios);

                var elementos = db.lab_Elementos.Where(p => p.lab_Estudios.Contains(p.lab_Estudios.FirstOrDefault(e => e.Id == guidIdEstudio))).Select(a => new
                {
                    a.Id,
                    a.Nombre,
                    a.UnidadMedida,
                    a.Notas
                }).ToList();

                var obj_x_estudio = JsonConvert.SerializeObject(new { elementos });

                return obj_x_estudio;
            }

        }

        [HttpPost]
        public string BorrarElemento(string value,string idEstudios)
        {
            try
            {
                if (idEstudios != null)
                {
                    var guidIdEstudio = Guid.Parse(idEstudios);
                    var estudio = db.lab_Estudios.Find(guidIdEstudio);

                    var guidValue = Guid.Parse(value);
                    var elemento = db.lab_Elementos.Find(guidValue);

                    estudio.lab_Elementos.Remove(elemento);
                    db.lab_Elementos.Remove(elemento);
                    db.SaveChanges();
                    return "Ok";
                }

                return "Inner Error";
            }
            catch (Exception e)
            {
                return "Error";
            }
        }
        
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lab_Elementos lab_Elementos = db.lab_Elementos.Find(id);
            if (lab_Elementos == null)
            {
                return HttpNotFound();
            }
            return View(lab_Elementos);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre,UnidadMedida,Notas")] lab_Elementos lab_Elementos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lab_Elementos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lab_Elementos);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Laboratorio.Core.MVC/Areas/Servicios/Views/Elementos/Edit.cshtml
@model Laboratorio.Core.DAL.Data.lab_Elementos

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_NiftyLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>lab_Elementos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadMedida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnidadMedida, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnidadMedida, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Laboratorio.Core.MVC/Areas/Servicios/Views/Elementos/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

<div id="app-elementos">
    <div class="panel" v-show="showPanel">
        <div class="panel-heading">
            <h3 class="panel-title">Elementos</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12 text-sm pad-btm">Agregar un nuevo elemento:</div>
                <div class="col-md-4 mar-btm">
                    <input v-model="elemento.nombre" type="text" class="form-control" placeholder="Nombre">
                </div>
                <div class="col-md-4 mar-btm">
                    <input v-model="elemento.unidadMedida" type="text" class="form-control" placeholder="Unidad de Medida">
                </div>
                <div class="col-md-4 mar-btm">
                    <input v-model="elemento.notas" type="text" class="form-control" placeholder="Notas">
                </div>
            </div>
            <div class="row text-right pad-btm">
                <div class="col-md-12">
                    <button v-on:click="submitData" class="btn btn-rounded btn-primary">Agregar elemento</button>
                </div>
            </div>
            <div class="list-group">
                <li v-for="elemento in elementos" class="list-group-item">
                    <span class="pull-right text-bold">
                        <button v-on:click="removeElement(elemento.Id)" class="btn btn-dark btn-xs btn-circle">
                            <i class="fa fa-close"></i>
                        </button>
                    </span>

                    <h5 class="list-group-item-heading">{{elemento.Nombre}} <span class="text-thin">({{elemento.UnidadMedida}})</span></h5>
                    <em>{{elemento.Notas}}</em>

                </li>
            </div>
        </div>
    </div>
</div>

<script>
    const appElementos = new Vue({
        el: '#app-elementos',
        data: {
            elementos: [],
            elemento: {
                nombre: '',
                unidadMedida: '',
                notas: ''
            },
            showPanel: false
        },
        created() {
            @*fetch('@Url.Action("ObtenerElementos", "Elementos")')
                .then(response => response.json())
                .then(json => { this.elementos = json.elementos });*@
        },
        methods: {
            submitData(event) {
                if (appElementos.elemento.nombre !== "" && appElementos.elemento.unidadMedida !== "" && appElementos.elemento.notas !== "") {
                    event.preventDefault();
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("CrearElemento", "Elementos")?idEstudio=' + appEstudios.activeIndex,
                        data: this.elemento,
                        success: function (result, status, xhr) {
                            if (result.includes("Error")) {
                                msgAlert(result, "danger");
                            } else {
                                appElementos.elemento = {
                                    nombre: '',
                                    unidadMedida: '',
                                    notas: ''
                                };
                                appElementos.refresh(appEstudios.activeIndex);
                            }
                        },
                        error: function (xhr, status, error) {
                            var msg = '<span class="text-bold">' + error + '</span><br/>Estatus: ' + xhr.status + '<br/>Descripción: ' + xhr.statusText;
                            msgAlert(msg, "danger");
                        }
                    });
                } else {
                    msgAlert("Campos vacíos", "warning");
                }
            },
            refresh(idEstudios) {
                fetch('@Url.Action("ObtenerElementos", "Elementos")/?idEstudios=' + idEstudios)
                    .then(response => response.json())
                    .then(json => { this.elementos = json.elementos });
                this.showPanel = true;
            },
            removeElement(value) {
                debugger 
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("BorrarElemento", "Elementos")/?idEstudios='+appEstudios.activeIndex,
                    data: { value },
                    success: function (result, status, xhr) {
                        if (result.includes("Error")) {
                            msgAlert(result, "danger");
                        } else {
                            appElementos.refresh(appEstudios.activeIndex);
                        }
                    },
                    error: function (xhr, status, error) {
                        var msg = '<span class="text-bold">' +
                            error +
                            '</span><br/>Estatus: ' +
                            xhr.status +
                            '<br/>Descripción: ' +
                            xhr.statusText;
                        msgAlert(msg, "danger");
                    }
                });
            },
            removeElementsFromList() {
                this.elementos = [];
                this.showPanel = false;
            }
        }
    });

    function msgAlert(message, type) {
        $.niftyNoty({
            type: type,
            icon: 'demo-pli-information icon-3x',
            message: message,
            container: 'floating',
            timer: 10000
        });
    }
</script>